task:
  freebsd_instance:
    image_family: freebsd-14-2
  env:
    PKG_CONFIG_PATH: /usr/local/lib/pkgconfig
    LD_LIBRARY_PATH: /usr/local/lib
    PATH: ${PATH}:/usr/local/sbin:/usr/sbin
    TPM2TOOLS_TCTI: "tabrmd:bus_name=com.intel.tss2.Tabrmd"
    TPM2OPENSSL_TCTI: ${TPM2TOOLS_TCTI}
    IBMSWTPM_VER: rev183-2024-08-02
    TPM2_TEST_HASHES: "sha1 sha256 sha384 sha512"

  install_packages_script: |
    pkg install -y bash wget gmake libtool pkgconf automake autoconf autoconf-archive \
                   git dbus openssl tpm2-tss tpm2-abrmd tpm2-tools
    service dbus enable
    service dbus start

  build_script: |
    ./bootstrap
    ./configure --enable-op-digest --enable-op-cipher
    gmake

  build_simulator_script: |
    wget --no-verbose https://github.com/kgoldman/ibmswtpm2/archive/refs/tags/$IBMSWTPM_VER.tar.gz
    tar xfz rev183-2024-08-02.tar.gz
    cd ibmswtpm2-$IBMSWTPM_VER/src
    sed -i '' -e 's/gcc/clang/g' makefile
    sed -i '' -e 's/-Wall //g' makefile
    sed -i '' -e 's/-Werror //g' makefile
    gmake

  run_simulator_background_script:
    ibmswtpm2-$IBMSWTPM_VER/src/tpm_server

  run_abrmd_background_script: |
    sudo -u _tss tpm2-abrmd --tcti mssim:host=localhost,port=2321

  check_script: |
    openssl version
    tpm2_getcap properties-fixed | head -n 20
    gmake check

  always:
    log_artifacts:
      path: test/**/*.log
      type: text/plain
