name: gcc-distcheck
on:
  [push, pull_request]
env:
  IBMSWTPM_VER: rev183-2024-08-02
  # sha1 is not tested by default because Fedora 41+ does not support it
  TPM2_TEST_HASHES: "sha1 sha256 sha384 sha512"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install curl autoconf-archive lcov libtss2-dev libtss2-tcti-tabrmd0 tpm2-abrmd tpm2-tools

    - name: Build TPM2 simulator
      run: |
        curl -Ls https://github.com/kgoldman/ibmswtpm2/archive/refs/tags/$IBMSWTPM_VER.tar.gz | tar xz
        cd ibmswtpm2-$IBMSWTPM_VER/src
        make

    - name: Configure tpm2-openssl
      run: |
        ./bootstrap
        ./configure CC=gcc --enable-op-digest --enable-op-cipher --enable-code-coverage --enable-debug

    - name: Build tpm2-openssl
      run: |
        make
        sudo make install

    - name: Start TPM2 simulator
      run: |
        export DBUS_SESSION_BUS_ADDRESS=`dbus-daemon --session --print-address --fork`
        echo "DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS" >> $GITHUB_ENV
        ibmswtpm2-$IBMSWTPM_VER/src/tpm_server &
        timeout 20 bash -c 'until printf "" 2>>/dev/null >>/dev/tcp/$0/$1; do sleep 1; done' localhost 2321
        tpm2-abrmd --session --tcti mssim:host=localhost,port=2321 &
        echo "TCTI_ADDRESS=tabrmd:bus_name=com.intel.tss2.Tabrmd,bus_type=session" >> $GITHUB_ENV
        sleep 1

    - name: Check code coverage
      run: |
        openssl version
        tpm2_getcap properties-fixed | head -n 20
        make check-code-coverage
      env:
        TPM2TOOLS_TCTI: ${{ env.TCTI_ADDRESS }}
        TPM2OPENSSL_TCTI: ${{ env.TCTI_ADDRESS }}

    - name: Submit code coverage
      uses: codecov/codecov-action@v5

    - name: Check the distribution
      # AM_DISTCHECK_CONFIGURE_FLAGS are not ready for clang and asan
      run: |
        make distcheck
      env:
        TPM2TOOLS_TCTI: ${{ env.TCTI_ADDRESS }}
        TPM2OPENSSL_TCTI: ${{ env.TCTI_ADDRESS }}

    - name: Archive log files
      if: ${{ success() || failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: test-report-gcc
        path: |
          *.log
          test/*.log
          test/*/*.log
          tpm2-openssl-*/_build/sub/test/*.log
          tpm2-openssl-*/_build/sub/test/*/*.log
